// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/trustbloc/sidetree-fabric/pkg/peer/discovery"
)

type DiscoveryProvider struct {
	UpdateLocalServicesForChannelStub        func(channelID string, services []discovery.Service)
	updateLocalServicesForChannelMutex       sync.RWMutex
	updateLocalServicesForChannelArgsForCall []struct {
		channelID string
		services  []discovery.Service
	}
	ServicesForChannelStub        func(channelID string) []discovery.Service
	servicesForChannelMutex       sync.RWMutex
	servicesForChannelArgsForCall []struct {
		channelID string
	}
	servicesForChannelReturns struct {
		result1 []discovery.Service
	}
	servicesForChannelReturnsOnCall map[int]struct {
		result1 []discovery.Service
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DiscoveryProvider) UpdateLocalServicesForChannel(channelID string, services []discovery.Service) {
	var servicesCopy []discovery.Service
	if services != nil {
		servicesCopy = make([]discovery.Service, len(services))
		copy(servicesCopy, services)
	}
	fake.updateLocalServicesForChannelMutex.Lock()
	fake.updateLocalServicesForChannelArgsForCall = append(fake.updateLocalServicesForChannelArgsForCall, struct {
		channelID string
		services  []discovery.Service
	}{channelID, servicesCopy})
	fake.recordInvocation("UpdateLocalServicesForChannel", []interface{}{channelID, servicesCopy})
	fake.updateLocalServicesForChannelMutex.Unlock()
	if fake.UpdateLocalServicesForChannelStub != nil {
		fake.UpdateLocalServicesForChannelStub(channelID, services)
	}
}

func (fake *DiscoveryProvider) UpdateLocalServicesForChannelCallCount() int {
	fake.updateLocalServicesForChannelMutex.RLock()
	defer fake.updateLocalServicesForChannelMutex.RUnlock()
	return len(fake.updateLocalServicesForChannelArgsForCall)
}

func (fake *DiscoveryProvider) UpdateLocalServicesForChannelArgsForCall(i int) (string, []discovery.Service) {
	fake.updateLocalServicesForChannelMutex.RLock()
	defer fake.updateLocalServicesForChannelMutex.RUnlock()
	return fake.updateLocalServicesForChannelArgsForCall[i].channelID, fake.updateLocalServicesForChannelArgsForCall[i].services
}

func (fake *DiscoveryProvider) ServicesForChannel(channelID string) []discovery.Service {
	fake.servicesForChannelMutex.Lock()
	ret, specificReturn := fake.servicesForChannelReturnsOnCall[len(fake.servicesForChannelArgsForCall)]
	fake.servicesForChannelArgsForCall = append(fake.servicesForChannelArgsForCall, struct {
		channelID string
	}{channelID})
	fake.recordInvocation("ServicesForChannel", []interface{}{channelID})
	fake.servicesForChannelMutex.Unlock()
	if fake.ServicesForChannelStub != nil {
		return fake.ServicesForChannelStub(channelID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.servicesForChannelReturns.result1
}

func (fake *DiscoveryProvider) ServicesForChannelCallCount() int {
	fake.servicesForChannelMutex.RLock()
	defer fake.servicesForChannelMutex.RUnlock()
	return len(fake.servicesForChannelArgsForCall)
}

func (fake *DiscoveryProvider) ServicesForChannelArgsForCall(i int) string {
	fake.servicesForChannelMutex.RLock()
	defer fake.servicesForChannelMutex.RUnlock()
	return fake.servicesForChannelArgsForCall[i].channelID
}

func (fake *DiscoveryProvider) ServicesForChannelReturns(result1 []discovery.Service) {
	fake.ServicesForChannelStub = nil
	fake.servicesForChannelReturns = struct {
		result1 []discovery.Service
	}{result1}
}

func (fake *DiscoveryProvider) ServicesForChannelReturnsOnCall(i int, result1 []discovery.Service) {
	fake.ServicesForChannelStub = nil
	if fake.servicesForChannelReturnsOnCall == nil {
		fake.servicesForChannelReturnsOnCall = make(map[int]struct {
			result1 []discovery.Service
		})
	}
	fake.servicesForChannelReturnsOnCall[i] = struct {
		result1 []discovery.Service
	}{result1}
}

func (fake *DiscoveryProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.updateLocalServicesForChannelMutex.RLock()
	defer fake.updateLocalServicesForChannelMutex.RUnlock()
	fake.servicesForChannelMutex.RLock()
	defer fake.servicesForChannelMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DiscoveryProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
