// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"
)

type RESTServerController struct {
	RestartRESTServerStub        func()
	restartRESTServerMutex       sync.RWMutex
	restartRESTServerArgsForCall []struct{}
	invocations                  map[string][][]interface{}
	invocationsMutex             sync.RWMutex
}

func (fake *RESTServerController) RestartRESTService() {
	fake.restartRESTServerMutex.Lock()
	fake.restartRESTServerArgsForCall = append(fake.restartRESTServerArgsForCall, struct{}{})
	fake.recordInvocation("RestartRESTService", []interface{}{})
	fake.restartRESTServerMutex.Unlock()
	if fake.RestartRESTServerStub != nil {
		fake.RestartRESTServerStub()
	}
}

func (fake *RESTServerController) RestartRESTServerCallCount() int {
	fake.restartRESTServerMutex.RLock()
	defer fake.restartRESTServerMutex.RUnlock()
	return len(fake.restartRESTServerArgsForCall)
}

func (fake *RESTServerController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.restartRESTServerMutex.RLock()
	defer fake.restartRESTServerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RESTServerController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
