// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"
)

type RESTServerController struct {
	RestartRESTServiceStub        func()
	restartRESTServiceMutex       sync.RWMutex
	restartRESTServiceArgsForCall []struct{}
	invocations                   map[string][][]interface{}
	invocationsMutex              sync.RWMutex
}

func (fake *RESTServerController) RestartRESTService() {
	fake.restartRESTServiceMutex.Lock()
	fake.restartRESTServiceArgsForCall = append(fake.restartRESTServiceArgsForCall, struct{}{})
	fake.recordInvocation("RestartRESTService", []interface{}{})
	fake.restartRESTServiceMutex.Unlock()
	if fake.RestartRESTServiceStub != nil {
		fake.RestartRESTServiceStub()
	}
}

func (fake *RESTServerController) RestartRESTServiceCallCount() int {
	fake.restartRESTServiceMutex.RLock()
	defer fake.restartRESTServiceMutex.RUnlock()
	return len(fake.restartRESTServiceArgsForCall)
}

func (fake *RESTServerController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.restartRESTServiceMutex.RLock()
	defer fake.restartRESTServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RESTServerController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
