// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	protocolApi "github.com/trustbloc/sidetree-core-go/pkg/api/protocol"
	"github.com/trustbloc/sidetree-fabric/pkg/peer/config"
)

type SidetreeConfigService struct {
	LoadProtocolsStub        func(namespace string) (map[string]protocolApi.Protocol, error)
	loadProtocolsMutex       sync.RWMutex
	loadProtocolsArgsForCall []struct {
		namespace string
	}
	loadProtocolsReturns struct {
		result1 map[string]protocolApi.Protocol
		result2 error
	}
	loadProtocolsReturnsOnCall map[int]struct {
		result1 map[string]protocolApi.Protocol
		result2 error
	}
	LoadSidetreeStub        func(namespace string) (config.Sidetree, error)
	loadSidetreeMutex       sync.RWMutex
	loadSidetreeArgsForCall []struct {
		namespace string
	}
	loadSidetreeReturns struct {
		result1 config.Sidetree
		result2 error
	}
	loadSidetreeReturnsOnCall map[int]struct {
		result1 config.Sidetree
		result2 error
	}
	LoadSidetreePeerStub        func(mspID, peerID string) (config.SidetreePeer, error)
	loadSidetreePeerMutex       sync.RWMutex
	loadSidetreePeerArgsForCall []struct {
		mspID  string
		peerID string
	}
	loadSidetreePeerReturns struct {
		result1 config.SidetreePeer
		result2 error
	}
	loadSidetreePeerReturnsOnCall map[int]struct {
		result1 config.SidetreePeer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SidetreeConfigService) LoadProtocols(namespace string) (map[string]protocolApi.Protocol, error) {
	fake.loadProtocolsMutex.Lock()
	ret, specificReturn := fake.loadProtocolsReturnsOnCall[len(fake.loadProtocolsArgsForCall)]
	fake.loadProtocolsArgsForCall = append(fake.loadProtocolsArgsForCall, struct {
		namespace string
	}{namespace})
	fake.recordInvocation("LoadProtocols", []interface{}{namespace})
	fake.loadProtocolsMutex.Unlock()
	if fake.LoadProtocolsStub != nil {
		return fake.LoadProtocolsStub(namespace)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.loadProtocolsReturns.result1, fake.loadProtocolsReturns.result2
}

func (fake *SidetreeConfigService) LoadProtocolsCallCount() int {
	fake.loadProtocolsMutex.RLock()
	defer fake.loadProtocolsMutex.RUnlock()
	return len(fake.loadProtocolsArgsForCall)
}

func (fake *SidetreeConfigService) LoadProtocolsArgsForCall(i int) string {
	fake.loadProtocolsMutex.RLock()
	defer fake.loadProtocolsMutex.RUnlock()
	return fake.loadProtocolsArgsForCall[i].namespace
}

func (fake *SidetreeConfigService) LoadProtocolsReturns(result1 map[string]protocolApi.Protocol, result2 error) {
	fake.LoadProtocolsStub = nil
	fake.loadProtocolsReturns = struct {
		result1 map[string]protocolApi.Protocol
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) LoadProtocolsReturnsOnCall(i int, result1 map[string]protocolApi.Protocol, result2 error) {
	fake.LoadProtocolsStub = nil
	if fake.loadProtocolsReturnsOnCall == nil {
		fake.loadProtocolsReturnsOnCall = make(map[int]struct {
			result1 map[string]protocolApi.Protocol
			result2 error
		})
	}
	fake.loadProtocolsReturnsOnCall[i] = struct {
		result1 map[string]protocolApi.Protocol
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) LoadSidetree(namespace string) (config.Sidetree, error) {
	fake.loadSidetreeMutex.Lock()
	ret, specificReturn := fake.loadSidetreeReturnsOnCall[len(fake.loadSidetreeArgsForCall)]
	fake.loadSidetreeArgsForCall = append(fake.loadSidetreeArgsForCall, struct {
		namespace string
	}{namespace})
	fake.recordInvocation("LoadSidetree", []interface{}{namespace})
	fake.loadSidetreeMutex.Unlock()
	if fake.LoadSidetreeStub != nil {
		return fake.LoadSidetreeStub(namespace)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.loadSidetreeReturns.result1, fake.loadSidetreeReturns.result2
}

func (fake *SidetreeConfigService) LoadSidetreeCallCount() int {
	fake.loadSidetreeMutex.RLock()
	defer fake.loadSidetreeMutex.RUnlock()
	return len(fake.loadSidetreeArgsForCall)
}

func (fake *SidetreeConfigService) LoadSidetreeArgsForCall(i int) string {
	fake.loadSidetreeMutex.RLock()
	defer fake.loadSidetreeMutex.RUnlock()
	return fake.loadSidetreeArgsForCall[i].namespace
}

func (fake *SidetreeConfigService) LoadSidetreeReturns(result1 config.Sidetree, result2 error) {
	fake.LoadSidetreeStub = nil
	fake.loadSidetreeReturns = struct {
		result1 config.Sidetree
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) LoadSidetreeReturnsOnCall(i int, result1 config.Sidetree, result2 error) {
	fake.LoadSidetreeStub = nil
	if fake.loadSidetreeReturnsOnCall == nil {
		fake.loadSidetreeReturnsOnCall = make(map[int]struct {
			result1 config.Sidetree
			result2 error
		})
	}
	fake.loadSidetreeReturnsOnCall[i] = struct {
		result1 config.Sidetree
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) LoadSidetreePeer(mspID string, peerID string) (config.SidetreePeer, error) {
	fake.loadSidetreePeerMutex.Lock()
	ret, specificReturn := fake.loadSidetreePeerReturnsOnCall[len(fake.loadSidetreePeerArgsForCall)]
	fake.loadSidetreePeerArgsForCall = append(fake.loadSidetreePeerArgsForCall, struct {
		mspID  string
		peerID string
	}{mspID, peerID})
	fake.recordInvocation("LoadSidetreePeer", []interface{}{mspID, peerID})
	fake.loadSidetreePeerMutex.Unlock()
	if fake.LoadSidetreePeerStub != nil {
		return fake.LoadSidetreePeerStub(mspID, peerID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.loadSidetreePeerReturns.result1, fake.loadSidetreePeerReturns.result2
}

func (fake *SidetreeConfigService) LoadSidetreePeerCallCount() int {
	fake.loadSidetreePeerMutex.RLock()
	defer fake.loadSidetreePeerMutex.RUnlock()
	return len(fake.loadSidetreePeerArgsForCall)
}

func (fake *SidetreeConfigService) LoadSidetreePeerArgsForCall(i int) (string, string) {
	fake.loadSidetreePeerMutex.RLock()
	defer fake.loadSidetreePeerMutex.RUnlock()
	return fake.loadSidetreePeerArgsForCall[i].mspID, fake.loadSidetreePeerArgsForCall[i].peerID
}

func (fake *SidetreeConfigService) LoadSidetreePeerReturns(result1 config.SidetreePeer, result2 error) {
	fake.LoadSidetreePeerStub = nil
	fake.loadSidetreePeerReturns = struct {
		result1 config.SidetreePeer
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) LoadSidetreePeerReturnsOnCall(i int, result1 config.SidetreePeer, result2 error) {
	fake.LoadSidetreePeerStub = nil
	if fake.loadSidetreePeerReturnsOnCall == nil {
		fake.loadSidetreePeerReturnsOnCall = make(map[int]struct {
			result1 config.SidetreePeer
			result2 error
		})
	}
	fake.loadSidetreePeerReturnsOnCall[i] = struct {
		result1 config.SidetreePeer
		result2 error
	}{result1, result2}
}

func (fake *SidetreeConfigService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.loadProtocolsMutex.RLock()
	defer fake.loadProtocolsMutex.RUnlock()
	fake.loadSidetreeMutex.RLock()
	defer fake.loadSidetreeMutex.RUnlock()
	fake.loadSidetreePeerMutex.RLock()
	defer fake.loadSidetreePeerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SidetreeConfigService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.SidetreeService = new(SidetreeConfigService)
