// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	batchapi "github.com/trustbloc/sidetree-core-go/pkg/api/batch"
	"github.com/trustbloc/sidetree-core-go/pkg/api/protocol"
	"github.com/trustbloc/sidetree-core-go/pkg/api/txn"
)

type OperationProvider struct {
	GetTxnOperationsStub        func(sidetreeTxn *txn.SidetreeTxn) ([]*batchapi.AnchoredOperation, error)
	getTxnOperationsMutex       sync.RWMutex
	getTxnOperationsArgsForCall []struct {
		sidetreeTxn *txn.SidetreeTxn
	}
	getTxnOperationsReturns struct {
		result1 []*batchapi.AnchoredOperation
		result2 error
	}
	getTxnOperationsReturnsOnCall map[int]struct {
		result1 []*batchapi.AnchoredOperation
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *OperationProvider) GetTxnOperations(sidetreeTxn *txn.SidetreeTxn) ([]*batchapi.AnchoredOperation, error) {
	fake.getTxnOperationsMutex.Lock()
	ret, specificReturn := fake.getTxnOperationsReturnsOnCall[len(fake.getTxnOperationsArgsForCall)]
	fake.getTxnOperationsArgsForCall = append(fake.getTxnOperationsArgsForCall, struct {
		sidetreeTxn *txn.SidetreeTxn
	}{sidetreeTxn})
	fake.recordInvocation("GetTxnOperations", []interface{}{sidetreeTxn})
	fake.getTxnOperationsMutex.Unlock()
	if fake.GetTxnOperationsStub != nil {
		return fake.GetTxnOperationsStub(sidetreeTxn)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getTxnOperationsReturns.result1, fake.getTxnOperationsReturns.result2
}

func (fake *OperationProvider) GetTxnOperationsCallCount() int {
	fake.getTxnOperationsMutex.RLock()
	defer fake.getTxnOperationsMutex.RUnlock()
	return len(fake.getTxnOperationsArgsForCall)
}

func (fake *OperationProvider) GetTxnOperationsArgsForCall(i int) *txn.SidetreeTxn {
	fake.getTxnOperationsMutex.RLock()
	defer fake.getTxnOperationsMutex.RUnlock()
	return fake.getTxnOperationsArgsForCall[i].sidetreeTxn
}

func (fake *OperationProvider) GetTxnOperationsReturns(result1 []*batchapi.AnchoredOperation, result2 error) {
	fake.GetTxnOperationsStub = nil
	fake.getTxnOperationsReturns = struct {
		result1 []*batchapi.AnchoredOperation
		result2 error
	}{result1, result2}
}

func (fake *OperationProvider) GetTxnOperationsReturnsOnCall(i int, result1 []*batchapi.AnchoredOperation, result2 error) {
	fake.GetTxnOperationsStub = nil
	if fake.getTxnOperationsReturnsOnCall == nil {
		fake.getTxnOperationsReturnsOnCall = make(map[int]struct {
			result1 []*batchapi.AnchoredOperation
			result2 error
		})
	}
	fake.getTxnOperationsReturnsOnCall[i] = struct {
		result1 []*batchapi.AnchoredOperation
		result2 error
	}{result1, result2}
}

func (fake *OperationProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getTxnOperationsMutex.RLock()
	defer fake.getTxnOperationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *OperationProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ protocol.OperationProvider = new(OperationProvider)
