// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	txnapi "github.com/trustbloc/fabric-peer-ext/pkg/txn/api"
)

type TxnServiceProvider struct {
	ForChannelStub        func(channelID string) (txnapi.Service, error)
	forChannelMutex       sync.RWMutex
	forChannelArgsForCall []struct {
		channelID string
	}
	forChannelReturns struct {
		result1 txnapi.Service
		result2 error
	}
	forChannelReturnsOnCall map[int]struct {
		result1 txnapi.Service
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TxnServiceProvider) ForChannel(channelID string) (txnapi.Service, error) {
	fake.forChannelMutex.Lock()
	ret, specificReturn := fake.forChannelReturnsOnCall[len(fake.forChannelArgsForCall)]
	fake.forChannelArgsForCall = append(fake.forChannelArgsForCall, struct {
		channelID string
	}{channelID})
	fake.recordInvocation("ForChannel", []interface{}{channelID})
	fake.forChannelMutex.Unlock()
	if fake.ForChannelStub != nil {
		return fake.ForChannelStub(channelID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.forChannelReturns.result1, fake.forChannelReturns.result2
}

func (fake *TxnServiceProvider) ForChannelCallCount() int {
	fake.forChannelMutex.RLock()
	defer fake.forChannelMutex.RUnlock()
	return len(fake.forChannelArgsForCall)
}

func (fake *TxnServiceProvider) ForChannelArgsForCall(i int) string {
	fake.forChannelMutex.RLock()
	defer fake.forChannelMutex.RUnlock()
	return fake.forChannelArgsForCall[i].channelID
}

func (fake *TxnServiceProvider) ForChannelReturns(result1 txnapi.Service, result2 error) {
	fake.ForChannelStub = nil
	fake.forChannelReturns = struct {
		result1 txnapi.Service
		result2 error
	}{result1, result2}
}

func (fake *TxnServiceProvider) ForChannelReturnsOnCall(i int, result1 txnapi.Service, result2 error) {
	fake.ForChannelStub = nil
	if fake.forChannelReturnsOnCall == nil {
		fake.forChannelReturnsOnCall = make(map[int]struct {
			result1 txnapi.Service
			result2 error
		})
	}
	fake.forChannelReturnsOnCall[i] = struct {
		result1 txnapi.Service
		result2 error
	}{result1, result2}
}

func (fake *TxnServiceProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.forChannelMutex.RLock()
	defer fake.forChannelMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TxnServiceProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
