// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-sdk-go/pkg/client/channel"
	"github.com/trustbloc/fabric-peer-ext/pkg/txn/api"
)

type TxnService struct {
	EndorseStub        func(req *api.Request) (resp *channel.Response, err error)
	endorseMutex       sync.RWMutex
	endorseArgsForCall []struct {
		req *api.Request
	}
	endorseReturns struct {
		result1 *channel.Response
		result2 error
	}
	endorseReturnsOnCall map[int]struct {
		result1 *channel.Response
		result2 error
	}
	EndorseAndCommitStub        func(req *api.Request) (resp *channel.Response, err error)
	endorseAndCommitMutex       sync.RWMutex
	endorseAndCommitArgsForCall []struct {
		req *api.Request
	}
	endorseAndCommitReturns struct {
		result1 *channel.Response
		result2 error
	}
	endorseAndCommitReturnsOnCall map[int]struct {
		result1 *channel.Response
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TxnService) Endorse(req *api.Request) (resp *channel.Response, err error) {
	fake.endorseMutex.Lock()
	ret, specificReturn := fake.endorseReturnsOnCall[len(fake.endorseArgsForCall)]
	fake.endorseArgsForCall = append(fake.endorseArgsForCall, struct {
		req *api.Request
	}{req})
	fake.recordInvocation("Endorse", []interface{}{req})
	fake.endorseMutex.Unlock()
	if fake.EndorseStub != nil {
		return fake.EndorseStub(req)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.endorseReturns.result1, fake.endorseReturns.result2
}

func (fake *TxnService) EndorseCallCount() int {
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	return len(fake.endorseArgsForCall)
}

func (fake *TxnService) EndorseArgsForCall(i int) *api.Request {
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	return fake.endorseArgsForCall[i].req
}

func (fake *TxnService) EndorseReturns(result1 *channel.Response, result2 error) {
	fake.EndorseStub = nil
	fake.endorseReturns = struct {
		result1 *channel.Response
		result2 error
	}{result1, result2}
}

func (fake *TxnService) EndorseReturnsOnCall(i int, result1 *channel.Response, result2 error) {
	fake.EndorseStub = nil
	if fake.endorseReturnsOnCall == nil {
		fake.endorseReturnsOnCall = make(map[int]struct {
			result1 *channel.Response
			result2 error
		})
	}
	fake.endorseReturnsOnCall[i] = struct {
		result1 *channel.Response
		result2 error
	}{result1, result2}
}

func (fake *TxnService) EndorseAndCommit(req *api.Request) (resp *channel.Response, err error) {
	fake.endorseAndCommitMutex.Lock()
	ret, specificReturn := fake.endorseAndCommitReturnsOnCall[len(fake.endorseAndCommitArgsForCall)]
	fake.endorseAndCommitArgsForCall = append(fake.endorseAndCommitArgsForCall, struct {
		req *api.Request
	}{req})
	fake.recordInvocation("EndorseAndCommit", []interface{}{req})
	fake.endorseAndCommitMutex.Unlock()
	if fake.EndorseAndCommitStub != nil {
		return fake.EndorseAndCommitStub(req)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.endorseAndCommitReturns.result1, fake.endorseAndCommitReturns.result2
}

func (fake *TxnService) EndorseAndCommitCallCount() int {
	fake.endorseAndCommitMutex.RLock()
	defer fake.endorseAndCommitMutex.RUnlock()
	return len(fake.endorseAndCommitArgsForCall)
}

func (fake *TxnService) EndorseAndCommitArgsForCall(i int) *api.Request {
	fake.endorseAndCommitMutex.RLock()
	defer fake.endorseAndCommitMutex.RUnlock()
	return fake.endorseAndCommitArgsForCall[i].req
}

func (fake *TxnService) EndorseAndCommitReturns(result1 *channel.Response, result2 error) {
	fake.EndorseAndCommitStub = nil
	fake.endorseAndCommitReturns = struct {
		result1 *channel.Response
		result2 error
	}{result1, result2}
}

func (fake *TxnService) EndorseAndCommitReturnsOnCall(i int, result1 *channel.Response, result2 error) {
	fake.EndorseAndCommitStub = nil
	if fake.endorseAndCommitReturnsOnCall == nil {
		fake.endorseAndCommitReturnsOnCall = make(map[int]struct {
			result1 *channel.Response
			result2 error
		})
	}
	fake.endorseAndCommitReturnsOnCall[i] = struct {
		result1 *channel.Response
		result2 error
	}{result1, result2}
}

func (fake *TxnService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	fake.endorseAndCommitMutex.RLock()
	defer fake.endorseAndCommitMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TxnService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Service = new(TxnService)
