// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/trustbloc/sidetree-core-go/pkg/processor"
)

type OpStoreClientProvider struct {
	GetStub        func(channelID, namespace string) processor.OperationStoreClient
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		channelID string
		namespace string
	}
	getReturns struct {
		result1 processor.OperationStoreClient
	}
	getReturnsOnCall map[int]struct {
		result1 processor.OperationStoreClient
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *OpStoreClientProvider) Get(channelID string, namespace string) processor.OperationStoreClient {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		channelID string
		namespace string
	}{channelID, namespace})
	fake.recordInvocation("Get", []interface{}{channelID, namespace})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(channelID, namespace)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getReturns.result1
}

func (fake *OpStoreClientProvider) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *OpStoreClientProvider) GetArgsForCall(i int) (string, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].channelID, fake.getArgsForCall[i].namespace
}

func (fake *OpStoreClientProvider) GetReturns(result1 processor.OperationStoreClient) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 processor.OperationStoreClient
	}{result1}
}

func (fake *OpStoreClientProvider) GetReturnsOnCall(i int, result1 processor.OperationStoreClient) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 processor.OperationStoreClient
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 processor.OperationStoreClient
	}{result1}
}

func (fake *OpStoreClientProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *OpStoreClientProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
