// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/trustbloc/sidetree-core-go/pkg/api/batch"
	"github.com/trustbloc/sidetree-core-go/pkg/processor"
)

type OperationStoreClient struct {
	GetStub        func(uniqueSuffix string) ([]*batch.Operation, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		uniqueSuffix string
	}
	getReturns struct {
		result1 []*batch.Operation
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 []*batch.Operation
		result2 error
	}
	PutStub        func(op *batch.Operation) error
	putMutex       sync.RWMutex
	putArgsForCall []struct {
		op *batch.Operation
	}
	putReturns struct {
		result1 error
	}
	putReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *OperationStoreClient) Get(uniqueSuffix string) ([]*batch.Operation, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		uniqueSuffix string
	}{uniqueSuffix})
	fake.recordInvocation("Get", []interface{}{uniqueSuffix})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(uniqueSuffix)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getReturns.result1, fake.getReturns.result2
}

func (fake *OperationStoreClient) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *OperationStoreClient) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].uniqueSuffix
}

func (fake *OperationStoreClient) GetReturns(result1 []*batch.Operation, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 []*batch.Operation
		result2 error
	}{result1, result2}
}

func (fake *OperationStoreClient) GetReturnsOnCall(i int, result1 []*batch.Operation, result2 error) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 []*batch.Operation
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 []*batch.Operation
		result2 error
	}{result1, result2}
}

func (fake *OperationStoreClient) Put(op *batch.Operation) error {
	fake.putMutex.Lock()
	ret, specificReturn := fake.putReturnsOnCall[len(fake.putArgsForCall)]
	fake.putArgsForCall = append(fake.putArgsForCall, struct {
		op *batch.Operation
	}{op})
	fake.recordInvocation("Put", []interface{}{op})
	fake.putMutex.Unlock()
	if fake.PutStub != nil {
		return fake.PutStub(op)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.putReturns.result1
}

func (fake *OperationStoreClient) PutCallCount() int {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return len(fake.putArgsForCall)
}

func (fake *OperationStoreClient) PutArgsForCall(i int) *batch.Operation {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return fake.putArgsForCall[i].op
}

func (fake *OperationStoreClient) PutReturns(result1 error) {
	fake.PutStub = nil
	fake.putReturns = struct {
		result1 error
	}{result1}
}

func (fake *OperationStoreClient) PutReturnsOnCall(i int, result1 error) {
	fake.PutStub = nil
	if fake.putReturnsOnCall == nil {
		fake.putReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *OperationStoreClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *OperationStoreClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.OperationStoreClient = new(OperationStoreClient)
